from dixxbot.statics import (
    GOAT_ROLE_ID,
    REDS_ROLE_ID,
    OPERATORS_ROLE_ID,
    GAME_LEADER_HLL_ROLE_ID,
    ADMIN_HLL_LEAD_ROLE_ID,
    ADMIN_HLL_SR_ROLE_ID,
    ADMIN_HLL_ROLE_ID,
    HLL_EVENT_STAFF_ROLE_ID,
    GAME_LEADER_SQD_ROLE_ID,
    ADMIN_SQD_LEAD_ROLE_ID,
    ADMIN_SQD_SR_ROLE_ID,
    ADMIN_SQD_ROLE_ID,
    GAME_LEADER_EFT_ROLE_ID,
    ADMIN_EFT_ROLE_ID,
    GAME_LEADER_HUNT_ROLE_ID,
    ADMIN_HUNT_ROLE_ID,
    GAME_LEADER_GB_ROLE_ID,
    ADMIN_GB_ROLE_ID,
    ONE_AD_ROLE_ID,
    BADGERS_ROLE_ID,
    BHB_ROLE_ID,
    EASY_ROLE_ID,
    MVG_ROLE_ID,
    STG_ROLE_ID,
    EGC_ROLE_ID,
    OS_ROLE_ID,
    THE_LINE_ROLE_ID,
    OSS_ROLE_ID,
    OSS_LEAD_ROLE_ID,
    OSS_SECTION_ROLE_ID,
    SOC_ROLE_ID,
    DB_ROLE_ID,
)

LEADERSHIP_ROLES = [GOAT_ROLE_ID, REDS_ROLE_ID, OPERATORS_ROLE_ID]

roles_add_remove = {
    ADMIN_HLL_LEAD_ROLE_ID: LEADERSHIP_ROLES + [GAME_LEADER_HLL_ROLE_ID],
    ADMIN_HLL_SR_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_HLL_ROLE_ID, ADMIN_HLL_LEAD_ROLE_ID],
    ADMIN_HLL_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_HLL_ROLE_ID, ADMIN_HLL_LEAD_ROLE_ID, ADMIN_HLL_SR_ROLE_ID],
    HLL_EVENT_STAFF_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_HLL_ROLE_ID, ADMIN_HLL_LEAD_ROLE_ID],
    ADMIN_SQD_LEAD_ROLE_ID: LEADERSHIP_ROLES + [GAME_LEADER_SQD_ROLE_ID],
    ADMIN_SQD_SR_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_SQD_ROLE_ID, ADMIN_SQD_LEAD_ROLE_ID],
    ADMIN_SQD_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_SQD_ROLE_ID, ADMIN_SQD_LEAD_ROLE_ID, ADMIN_SQD_SR_ROLE_ID],
    ADMIN_EFT_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_SQD_ROLE_ID, GAME_LEADER_EFT_ROLE_ID],
    ADMIN_HUNT_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_SQD_ROLE_ID, GAME_LEADER_HUNT_ROLE_ID],
    ADMIN_GB_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_SQD_ROLE_ID, GAME_LEADER_GB_ROLE_ID],
    ONE_AD_ROLE_ID: LEADERSHIP_ROLES + [ONE_AD_ROLE_ID, GAME_LEADER_HLL_ROLE_ID],
    BADGERS_ROLE_ID: LEADERSHIP_ROLES + [BADGERS_ROLE_ID, GAME_LEADER_HLL_ROLE_ID],
    BHB_ROLE_ID: LEADERSHIP_ROLES + [BHB_ROLE_ID, GAME_LEADER_HLL_ROLE_ID],
    EASY_ROLE_ID: LEADERSHIP_ROLES + [EASY_ROLE_ID],
    MVG_ROLE_ID: LEADERSHIP_ROLES + [MVG_ROLE_ID],
    STG_ROLE_ID: LEADERSHIP_ROLES + [STG_ROLE_ID, GAME_LEADER_SQD_ROLE_ID],
    EGC_ROLE_ID: LEADERSHIP_ROLES + [EGC_ROLE_ID, GAME_LEADER_SQD_ROLE_ID],
    OS_ROLE_ID: LEADERSHIP_ROLES + [OS_ROLE_ID, GAME_LEADER_SQD_ROLE_ID],
    THE_LINE_ROLE_ID: LEADERSHIP_ROLES + [THE_LINE_ROLE_ID, GAME_LEADER_HLL_ROLE_ID],
    OSS_ROLE_ID: LEADERSHIP_ROLES + [OSS_LEAD_ROLE_ID],
    OSS_SECTION_ROLE_ID: LEADERSHIP_ROLES + [OSS_LEAD_ROLE_ID],
    SOC_ROLE_ID: LEADERSHIP_ROLES
    + [GAME_LEADER_SQD_ROLE_ID, ADMIN_SQD_LEAD_ROLE_ID, ADMIN_SQD_SR_ROLE_ID],
    DB_ROLE_ID: LEADERSHIP_ROLES + [DB_ROLE_ID],
}
